// Generated by scripts/generate-events-snapshot-module.mjs. Do not edit by hand.
import type { EventsPayload } from './events';

export const embeddedEventsPayload = {
  "schemaVersion": 1,
  "provider": "finnhub",
  "generatedAt": "2026-10-02T19:22:56.672Z",
  "range": {
    "from": "2026-10-02",
    "to": "2026-10-09"
  },
  "earnings": [
    {
      "symbol": "AGSS",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "ALP",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "BABB",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "CBIH",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "COOT",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "CYCA",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "LNAI",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "MDRX",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "QH",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "VFS",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "epsEstimate": -0.3333,
      "revenueEstimate": 1160828350,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "VIVC",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "ZEOX",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "ZVSA",
      "date": "2026-10-02",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "AIO",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "ATGL",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "BRTX",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "epsEstimate": -2.55,
      "revenueEstimate": 341700,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "CYTOF",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "EQFN",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "FGNV",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "HPF",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "HTOO",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "INTE",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "MFON",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "MKC",
      "date": "2026-10-05",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": 0.7633,
      "revenueEstimate": 1997185291,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "MPCB",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "MXE",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "NCZ",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "NFJ",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "NIE",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "SBSAA",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "SPPL",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "TC",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "TRSG",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "VCIG",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "VWFB",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "WDSP",
      "date": "2026-10-05",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "ADVB",
      "date": "2026-10-06",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "ANVI",
      "date": "2026-10-06",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "APOG",
      "date": "2026-10-06",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": 0.6426,
      "revenueEstimate": 366653616,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "AXIL",
      "date": "2026-10-06",
      "session": "after-close",
      "timeLabel": "After Close",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "FBSI",
      "date": "2026-10-06",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "LW",
      "date": "2026-10-06",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": 0.606,
      "revenueEstimate": 1704374186,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "NEOG",
      "date": "2026-10-06",
      "session": "after-close",
      "timeLabel": "After Close",
      "epsEstimate": -0.0714,
      "revenueEstimate": 212338500,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "NKGN",
      "date": "2026-10-06",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "NXTT",
      "date": "2026-10-06",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "PENG",
      "date": "2026-10-06",
      "session": "after-close",
      "timeLabel": "After Close",
      "epsEstimate": 0.7844,
      "revenueEstimate": 524737643,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "RPM",
      "date": "2026-10-06",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": 1.966,
      "revenueEstimate": 2244893599,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "SAR",
      "date": "2026-10-06",
      "session": "after-close",
      "timeLabel": "After Close",
      "epsEstimate": 0.4946,
      "revenueEstimate": 32017404,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "STZ",
      "date": "2026-10-06",
      "session": "after-close",
      "timeLabel": "After Close",
      "epsEstimate": 3.6021,
      "revenueEstimate": 2568050876,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "WS",
      "date": "2026-10-06",
      "session": "after-close",
      "timeLabel": "After Close",
      "epsEstimate": 0.7004,
      "revenueEstimate": 912477000,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "APLD",
      "date": "2026-10-07",
      "session": "after-close",
      "timeLabel": "After Close",
      "epsEstimate": -0.3098,
      "revenueEstimate": 137557016,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "BKSC",
      "date": "2026-10-07",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "GLEI",
      "date": "2026-10-07",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "LEVI",
      "date": "2026-10-07",
      "session": "after-close",
      "timeLabel": "After Close",
      "epsEstimate": 0.3649,
      "revenueEstimate": 1647399450,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "LFS",
      "date": "2026-10-07",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "NRIX",
      "date": "2026-10-07",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "epsEstimate": -0.6129,
      "revenueEstimate": 24768150,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "RELL",
      "date": "2026-10-07",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "epsEstimate": 0.0918,
      "revenueEstimate": 60164700,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "RGP",
      "date": "2026-10-07",
      "session": "after-close",
      "timeLabel": "After Close",
      "epsEstimate": -0.1692,
      "revenueEstimate": 100983163,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "WELNF",
      "date": "2026-10-07",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "AMBK",
      "date": "2026-10-08",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "ANGO",
      "date": "2026-10-08",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": -0.1156,
      "revenueEstimate": 82110000,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "BYRN",
      "date": "2026-10-08",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": -0.1658,
      "revenueEstimate": 16587240,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "CIBH",
      "date": "2026-10-08",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "CNBB",
      "date": "2026-10-08",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "CYDY",
      "date": "2026-10-08",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "HELE",
      "date": "2026-10-08",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": 0.5151,
      "revenueEstimate": 452080575,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "INTG",
      "date": "2026-10-08",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "KARO",
      "date": "2026-10-08",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "epsEstimate": 9.578,
      "revenueEstimate": 1631194536,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "LOGN",
      "date": "2026-10-08",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "NG",
      "date": "2026-10-08",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": -0.0773,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "ODC",
      "date": "2026-10-08",
      "session": "after-close",
      "timeLabel": "After Close",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "PEP",
      "date": "2026-10-08",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": 2.319,
      "revenueEstimate": 25226779564,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "SODI",
      "date": "2026-10-08",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "TLRY",
      "date": "2026-10-08",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": -0.1948,
      "revenueEstimate": 273922020,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "CCEL",
      "date": "2026-10-09",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "epsEstimate": 0.0306,
      "revenueEstimate": 7602060,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "CLSD",
      "date": "2026-10-09",
      "session": "after-close",
      "timeLabel": "After Close",
      "epsEstimate": -0.2693,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "DAL",
      "date": "2026-10-09",
      "session": "before-open",
      "timeLabel": "Before Open",
      "epsEstimate": 1.9868,
      "revenueEstimate": 17778762279,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "HIFS",
      "date": "2026-10-09",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "HOVR",
      "date": "2026-10-09",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "epsEstimate": -0.134,
      "revenueEstimate": 0,
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "MLGF",
      "date": "2026-10-09",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    },
    {
      "symbol": "PBNC",
      "date": "2026-10-09",
      "session": "unknown",
      "timeLabel": "Time TBA",
      "impact": "Medium",
      "watchlistMatch": false
    }
  ]
} satisfies EventsPayload;
